### ISSUE TITLE
Is it possible to support CURA pause at height?

### ISSUE THREAD

**Issue by tsoyi** [KerseyFabrications/marlin_e5p#1]
Hi!

Before starting my E5P with this firmware, I just found this machine doesn't support CURA's pause at height / layer. It seems it need to enable below 3 features in Marlin. Will you enable those in next version? Thank you!

<Reference>

Pause at Height or Layer
Only Pause or Pause for filament change.

This plugin will only work with Marlin that has been configured with "Advanced Pause", "Park Head on Pause", and "Nozzle Park Feature."

Advanced Pause is located in the Configuration_adv.h of Marlin.

 /**
 * Advanced Pause
 * Experimental feature for filament change support and for parking the nozzle when paused.
 * Adds the GCode M600 for initiating filament change.
 * If PARK_HEAD_ON_PAUSE enabled, adds the GCode M125 to pause printing and park the nozzle.
 *
 * Requires an LCD display.
 * Requires NOZZLE_PARK_FEATURE.
 * This feature is required for the default FILAMENT_RUNOUT_SCRIPT.
 */
Nozzle Park Feature is located in Configuration.h

 /**
 * Nozzle Park
 *
 * Park the nozzle at the given XYZ position on idle or G27.
 *
 * The "P" parameter controls the action applied to the Z axis:
 *
 *    P0  (Default) If Z is below park Z raise the nozzle.
 *    P1  Raise the nozzle always to Z-park height.
 *    P2  Raise the nozzle by Z-park amount, limited to Z_MAX_POS.
 */
This plugin makes use of the M125 and M600 GCodes.
Without the above GCodes being active in the Marlin firmware this plugin will not operate.

**Comment by KerseyFabrications** [comment]
Yes. I'm going to do a build for the new release and I'll get these in there. It will probably be this weekend.

**Comment by tsoyi** [comment]
so great!! looking forward to your update!!

**Comment by tsoyi** [comment]
Not sure if it's easy to ￼modify it on such a touchscreen machine.

Is it a good idea to enable the support of 12864 screen module?

To remove the touch screen or have a secondary 12864 seems a compulsory course. Especially after Kersey push it￼.

**Comment by KerseyFabrications** [comment]
@tsoyi Did you want this built for the stock/silent mainboard or one of the Bigtreetech boards?

**Comment by tsoyi** [comment]
I need stock & BTT board, thank you!!

**Comment by emersonsc** [comment]
Has the m600 and m125 been added yet? I don't have a need for the SkR boards because I don't want to change the screen. I'd like to be able to use the stock and eventually silent board from Creality with your firmware. My prints must be able to use the m600 command. My ender 3 uses this with just a simple flash, the touch screen on the E5+ seems to make this very difficult and almost regret buying it.

**Comment by KerseyFabrications** [comment]
First, although you said it was not needed, I did add this to my last version of the SKR firmware.
Second, I am unable to enable this on the Ender 5 Plus with the stock display:
#error "ADVANCED_PAUSE_FEATURE currently requires an LCD controller."
If you'd like to switch out the touchscreen for the standard 12864 display (https://amzn.to/2Q2ZNfP), I could build a version of firmware for that. Then you could at least keep the stock board.
Sorry.
