### ISSUE TITLE
Aux leveling doesn’t work

### ISSUE THREAD

**Issue by tsoyi** [KerseyFabrications/marlin_e5p#2]
Just found I can't use the Aux Leveling. BL touch can move to the center of the bed, however, I didn't get any response when I pressed the five position buttons to change. Luckily,the return button still works, so it still allow me to cancel Aux Leveling and continue other operations.

**Comment by KerseyFabrications** [comment]
Which display are you using?

**Comment by tsoyi** [comment]
Hi Kersey, my E5+ use the stock control board and touch screen. Thank you!

**Comment by tsoyi** [comment]
Hi! Kersey, 

I actually don't believe it would be the firmware problem, so I tested again last night. It can work now!!

I never heard you have remote customer services!

Alter I updated the firmware I tried several times. I'm really sure that the five position buttons had no response all night and only return button was on duty. I don't know why.

Next time it happen again, I'll let you know.

Thank you!!!

**Comment by KerseyFabrications** [comment]
I'm really glad to hear that because this one confused me. :-)

**Comment by tsoyi** [comment]
Sorry for bothering you! I really appreciate your firmware!!

Best Regards,
程左一 Tsoyi Cheng



Kris Kersey <notifications@github.com> 於 2020年8月1日 週六 上午9:42寫道：

**Comment by tsoyi** [comment]
Hi KF,

I just found the RepRap Discount  Smart Controller is uncommented in the stock firmware. Do you also keep it uncommented in your modification?

I don’t know if it means it  can support such kind of controller?

I’m planning to get one to try. What do you think?

https://reprap.org/wiki/RepRapDiscount_Smart_Controller

Best Regards,
Tsoyi
