### ISSUE TITLE
Recent Creality Release

### ISSUE THREAD

**Issue by unitrix0** [KerseyFabrications/marlin_e5p#5]
Hey, I've just found your firmware. Thank you for this work. I always had issues getting ABL working and it never really helped. My question is, did creality adopt your changes? I'm asking that because they released a new firmware on March 9th. Or the other way around, does your firmware have the changes included from that recent release?

Thank you

**Comment by KerseyFabrications** [comment]
I've downloaded the new release labeled 1.70.3. There's no source code or release notes though, so I'll have to reach out to Creality to see what's been changed. Thanks for the heads-up.

**Comment by unitrix0** [comment]
Yes, I've also asked them about a change log. They are not so talkative about that.

**Comment by unitrix0** [comment]
Have you maybe already heard from them? Can't wait to have a working BLTouch 😊 
On the other hand I'm also looking for a working M600. Maybe I'm better off with changing to a Bigtreetech board?

**Comment by Hunv** [comment]
Hi,
my personal changelog until now:
- Language Chinese after every reboot
- Octoprint shows decimal values of the bed and noozle temperature
- The cancel/pause function when printing directly from the printer is not working

Currently I can't recommend the (official) updated firmware.

**Comment by KerseyFabrications** [comment]
Thanks @Hunv. @unitrix0 I have not heard from Creality and at this point, I don't think I will. I'm still trying to get to using it but @Hunv makes me think it's not worth it.

@Hunv, did you update the display firmware too?

**Comment by Hunv** [comment]
> Thanks @Hunv. @unitrix0 I have not heard from Creality and at this point, I don't think I will. I'm still trying to get to using it but @Hunv makes me think it's not worth it.
> 
> @Hunv, did you update the display firmware too?

No, I didn't.

**Comment by KerseyFabrications** [comment]
> > Thanks @Hunv. @unitrix0 I have not heard from Creality and at this point, I don't think I will. I'm still trying to get to using it but @Hunv makes me think it's not worth it.
> > @Hunv, did you update the display firmware too?
> 
> No, I didn't.

With some of the issues you've mentioned, you probably should update the display too if you want the latest. I'm guessing you have some mismatch between the display and the firmware. That being said, if you want to stick with my firmware, don't update the display.

**Comment by unitrix0** [comment]
Wow that all sounds quite disillusioning. I guess that's the point to switch to a Bigtreetech board then.

I think you have a video on this right? @KerseyFabrications

**Comment by robcode222** [comment]
Yep, was just recommend this firmware update and now everything is in Chinese.   I installed the Ender-5PlusBLTouch_0904_V1.71.0 KF PIDTEMPBED.hex.   I didn't see anything else that needed to be done in the video I followed.  Does the display firmware needed to be updated?  I'm not sure how to fix this issue and doesn't look like it has been solved here.

**Comment by robcode222** [comment]
@Hunv, @KerseyFabrications , @unitrix0


> Hi, my personal changelog until now:
> 
> * Language Chinese after every reboot
> * Octoprint shows decimal values of the bed and noozle temperature
> * The cancel/pause function when printing directly from the printer is not working
> 
> Currently I can't recommend the (official) updated firmware.



I had the same issue.  The FW install defaults to the Chinese language and if you don't know Chinese, you don't know how to select English.  

Press the middle button on the bottom row.  That is the language select button.  Then select English.

**Comment by KerseyFabrications** [comment]
@unitrix0 Yep. Several different ones.
@robcode222 I also have this short video: https://www.youtube.com/watch?v=2BroEvNYuvc

**Comment by dflament** [comment]
there's a message on the official creality firmware page from a user who fixed the 1.70.3 language problem (lcd stays in chinese)

> I fixed bad language . rename C/E files for lcd dwin firmware and woalaa !

**Comment by JimCad76** [comment]
A friend of mine bought a ender 5 plus and it shipped to him with your firmware installed, Kersey. Just thought you should be made aware if you aren't already.

**Comment by KerseyFabrications** [comment]
Thanks for the heads-up. I haven't heard of this from anyone else. I'm cool with it though.

**Comment by ooono-developer** [comment]
I just got my E5P 2 days ago, and it does not have Kersey's FW installed.

Ordered it directly from them here in Europe.
