### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by RickyBurton** [KerseyFabrications/marlin_e5p#6]
Hi, I have installed an skr 1.4 turbo and have no clue how to flash it to my board what is the best way ?

**Comment by jbeima** [comment]
You can't put this firmware on an anything other that the Creatily main board, you would need to compile your own version, which would then mean no screen support.

If you are going to that extent, you may want to just change over to Klipper.

**Comment by KerseyFabrications** [comment]
Please check out my Facebook (https://www.facebook.com/kerseyfabs/) and/or YouTube Community page (https://www.youtube.com/@kerseyfabs/community). I have my firmware and instructions there. Thanks!
