### ISSUE TITLE
Does it work on Silent Motherboard 2.2

### ISSUE THREAD

**Issue by ooono-developer** [KerseyFabrications/marlin_e5p#7]
Hi Kersey

Does your firmware work on the Creality Silent motherboard V2.2?

If yes, what firmware file should i download?

Thanks :)

p.s. Love your youtube channel

**Comment by KerseyFabrications** [comment]
If that's the one they're marketing to the Ender 5 Plus, it should work. It would be the same one you find in my video descriptions.
